#!/bin/bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
proc=$(ps aux | wc -l)
chss=$(hostnamectl | awk '/Vir/{print $2}')
chss=${chss:-dedi}
chss="$(hostnamectl | awk '/Cha/{print $2}') ( $chss )"
load=$(awk '{print $1, $2, $3}' /proc/loadavg)
tram=$(awk '/^MemT/{print int($2 / 1024) "MB"}' /proc/meminfo)
uram=$(awk '/^MemT/{ t=$2 } /^MemF/{ f=$2 } /^Cach/{ f+=$2 } /^Buff/{ f+=$2 } END { printf("%3.1f%%", (t-f)/t*100)}' /proc/meminfo)
ip4n=$(wget --timeout=4 --tries=1 -q4O- ip.rootnet.in)
ip4c=$(hostname -i)
tswa=$(awk '/^SwapT/{print int($2 / 1024) "MB"}' /proc/meminfo)
uswa="-"
[ "$tswa" != "0MB" ] && {
	uswa=$(awk '/^SwapT/{ t=$2 } /^SwapF/{ f=$2 } END { printf("%3.1f%%", (t-f)/t*100)}' /proc/meminfo)
}
time=$(uptime | sed -e 's/^[^,]*up *//' -e 's/, *[[:digit:]]* user.*//')
disk=$(df -kl / | awk '/\//{printf("%dGiB",$2/1048576)}')
uhdd=$(df -h / | awk '/\// {print $(NF-1)}')
date=$(date +'%F %T %z')
 
echo
printf "Chassis: %-16s\tSystem load:\t%s\n" "$chss" "$load / $proc proc"
printf "RAM:     %6s of %-6s\tIPv4: net [cfg]\t%s [ %s ]\n" "$uram" "$tram" "$ip4n" "$ip4c"
printf "Swap:    %6s of %-6s\tSystem uptime:\t%s\n" "$uswa" "$tswa" "$time"
printf "Storage: %6s of %-6s\tCurrent date:\t%s\n" "$uhdd" "$disk" "$date"
echo

