#!/bin/bash
#
#    10-sysinfo - generate the system information
#    Copyright (c) 2013 Nick Charlton
#
#    Authors: Nick Charlton <hello@nickcharlton.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 
proc=$(ps aux | wc -l)
load=$(awk '{print $1, $2, $3}' /proc/loadavg)
tram=$(awk '/^MemT/{print int($2 / 1024) "MB"}' /proc/meminfo)
mram=$(awk '/^MemT/{ t=$2 } /^MemF/{ f=$2 } /^Cach/{ f+=$2 } /^Buff/{ f+=$2 } END { printf("%3.1f%%", (t-f)/t*100)}' /proc/meminfo)
ipv4=$(hostname -i)
tswa=$(awk '/^SwapT/{print int($2 / 1024) "MB"}' /proc/meminfo)
swap=$(awk '/^SwapT/{ t=$2 } /^SwapF/{ f=$2 } END { printf("%3.1f%%", (t-f)/t*100)}' /proc/meminfo)
time=$(uptime | sed -e 's/^[^,]*up *//' -e 's/, *[[:digit:]]* user.*//')
disk=$(df -kl / | awk '/\//{printf("%dGiB",$2/1048576)}')
hdus=$(df -h / | awk '/\// {print $(NF-1)}')
date=$(date +'%F %T %z')
 
echo
printf "Processes:\t%s\tSystem load:\t%s\n" "$proc" "$load"
printf "RAM (%s):\t%s\tIP Address:\t%s\n" "$tram" "$mram" "$ipv4"
printf "Swap (%s):\t%s\tSystem uptime:\t%s\n" "$tswa" "$swap" "$time"
printf "HD / (%s):\t%s\tCurrent date:\t%s\n" "$disk" "$hdus" "$date"
echo

