#!/bin/bash
# ------------------------------------------------------------------------------
# forcing full hostname & load iptables rules
# ------------------------------------------------------------------------------

command hostname -f > /etc/hostname
command sysctl -qw kernel.hostname="$(command hostname -f)"

sed -ri "s/^(root:\s+).*/\1k-$(command hostname -s)@rete.us/" /etc/aliases
command newaliases

[ -s /etc/iptables.v4.rules ] && {
	command iptables-restore < /etc/iptables.v4.rules
#	:
}
[ -s /etc/iptables.v6.rules ] && {
	command ip6tables-restore < /etc/iptables.v6.rules
#	:
}
